# Configurations
title:            ChatGee AI 챗봇 빌더
longtitle:        ChatGee AI 챗봇 빌더
author:           Woen-Sug Choi
email:            talkchatgpt@gmail.com
description: >
  ChatGee AI 챗봇 빌더 사용설명서

version:          0.1
gitbook_version:  3.2.3

url:              'https://woensug-choi.github.io'
baseurl:          '/ChatGee'
rss:              RSS

tracker:
  google_analytics:

# bootstrap: use the remote theme for the site itself
remote_theme: woensug-choi/ChatGee
toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: github

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:        /:categories/:title:output_ext

# exclude:
#   - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 800px

destination:      ./_site
incremental:      false
regenerate:       true
future: true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
  - jekyll-toc
  - jekyll-last-modified-at

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%d-%b-%y'
